name: Site checks
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  check:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          persist-credentials: false
      - run: python3 check_site.py
